title:             shuqing's Blog
email:              xushuqing0575@gmail.com
description:        share my learning experiences in computer science.
author:             XU SHUQING 胥淑青
baseurl: ""
url:                "https://startbootstrap.github.io"

# Social Profiles
github_username:    xushuqing0575
Wechat_id: xushuqing705 
linkedin_username:  SHUQING XU
whatsapp_number: +8618753179516
# Add your google-analytics ID here to activate google analytics
google_analytics:   G-EPQJL9B1T7 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
